// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGU4kDCYUBC33I5uneag-XzOgTEsW2RIc',
    appId: '1:364253304301:web:0b047cf99ca40ef4f603e4',
    messagingSenderId: '364253304301',
    projectId: 'news-feed-d29f1',
    authDomain: 'news-feed-d29f1.firebaseapp.com',
    storageBucket: 'news-feed-d29f1.appspot.com',
    measurementId: 'G-QWG6JPPXBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU2Rvoh53pqHUlfnLZM3omRD6MQnNoMu4',
    appId: '1:364253304301:android:1c5ef02eae5031fbf603e4',
    messagingSenderId: '364253304301',
    projectId: 'news-feed-d29f1',
    storageBucket: 'news-feed-d29f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx9MCkCbwtNpXAlgYzKOTq3uWoaQW_Ccc',
    appId: '1:364253304301:ios:360856f714bf6753f603e4',
    messagingSenderId: '364253304301',
    projectId: 'news-feed-d29f1',
    storageBucket: 'news-feed-d29f1.appspot.com',
    iosBundleId: 'com.example.newsfeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx9MCkCbwtNpXAlgYzKOTq3uWoaQW_Ccc',
    appId: '1:364253304301:ios:5c8a6f77df4d03d4f603e4',
    messagingSenderId: '364253304301',
    projectId: 'news-feed-d29f1',
    storageBucket: 'news-feed-d29f1.appspot.com',
    iosBundleId: 'com.example.newsfeed.RunnerTests',
  );
}
